cache: bundler
language: ruby
sudo: false

rvm:
  - 2.4.0

services:
  - postgresql

script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

before_install:
  - gem update --system
  - gem --version
