version: '3'
services:
  db:
    image: postgres
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
  web:
    tty: true
    stdin_open: true
    build: .
    links:
      - mailcatcher
    volumes:
      - .:/myapp
    ports:
      - "3002:3002"
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
