pl:
  training:
    supplementary:
      sign_ups:
        create:
          limit_exceded: Brak miejsc!
          not_last_fee: Musisz opłacić składkę członkowską!
      course:
        enums:
          categories:
            kw: Ogólne
            sww: Wspinaczkowe
            snw: Narciarskie
            stj: Jaskiniowe
      courses:
        index:
          header: Szkolenia, spotkania i wyjazdy
        table:
          category: Kategoria
          submit: Zapisz się!
          name: Nazwa
          place: Miejsce
          date: Data
          organizer: Organizator
          price: Cena(zł)
          edit: Edycja
          show: Szczegóły
          sign_up: Zapisz się!
          limit: Zapisy
          destroy: Usuń
          sign_up_destroy: Wypisz się!
        show:
          submit: Zapisz się!
          sign_up_remarks: Twój e-mail zostanie usunięty z naszego systemu 24h po wydarzeniu.
          sign_up: Zapisz się!
          sign_up_destroy: Wypisz się!
          category: Kategoria
          rules: Link do regulaminu wydarzeń KW Kraków
          name: Nazwa
          place: "Miejsce: "
          start_date: "Od kiedy?: "
          end_date: "Do kiedy?: "
          application_date: "Do kiedy zapisy?: "
          organizer: "Organizator: "
          remarks: "Uwagi od organizatora"
          price_kw: "Cena dla klubowiczów: "
          price_non_kw: "Cena dla nie-klubowiczów: "
          edit: Edycja
          destroy: Usuń
        new:
          submit: Utwórz
          back: Cofnij
        edit:
          submit: Zaktualizuj
          back: Cofnij
        form:
          team_name: Nazwa
          last_fee_paid: Wymagaj opłaconej składki?
          category: Kategoria
          place: Miejsce
          open: Otwarte dla wszystkich?
          start_date: Kiedy?
          price: Wymagaj zaliczki?
          one_day: Tylko jeden dzień?
          end_date: Do kiedy
          application_date: Start zapisów
          price_kw: Zaliczka dla KW
          price_non_kw: Zaliczka dla reszty
          remarks: Uwagi od organizatora
          organizator_id: Kto organizuje?
