pl:
  training:
    supplementary:
      course:
        enums:
          categories:
            kw: Ogólne
            sww: Wspinaczkowe
            snw: Narciarskie
            stj: Jaskiniowe
      courses:
        table:
          category: Kategoria
          name: Nazwa
          place: Miejsce
          date: Data
          organizer: Organizator
          price: Cena(zł)
          edit: Edycja
          show: Szczegóły
          destroy: Usuń
        show:
          category: Kategoria
          name: Nazwa
          place: "Miejsce: "
          start_date: "Od kiedy?: "
          end_date: "Do kiedy?: "
          application_date: "Do kiedy zapisy?: "
          organizer: "Organizator: "
          remarks: "Uwagi od organizatora"
          price_kw: "Cena dla klubowiczów: "
          price_non_kw: "Cena dla nie-klubowiczów: "
          edit: Edycja
          destroy: Usuń
        new:
          submit: Utwórz
          back: Cofnij
        edit:
          submit: Zaktualizuj
          back: Cofnij
        form:
          team_name: Nazwa
          category: Kategoria
          place: Miejsce
          start_date: Kiedy?
          price: Zaliczka?
          one_day: Jeden dzień?
          end_date: Do kiedy
          application_date: Start zapisów
          price_kw: Zaliczka dla KW
          price_non_kw: Zaliczka dla reszty
          remarks: Uwagi od organizatora
          organizator_id: Kto organizuje?
