pl:
  training:
    supplementary:
      course:
        enums:
          categories:
            kw: Ogólne
            sww: Wspinaczkowe
            snw: Narciarskie
            stj: Jaskiniowe
      courses:
        new:
          submit: Utwórz
        edit:
          submit: Zaktualizuj
        form:
          team_name: Nazwa
          category: Kategoria
          place: Miejsce
          start_date: Od kiedy
          price: Zaliczka?
          one_day: Jeden dzień?
          end_date: Do kiedy
          application_date: Data zapisów
          price_kw: Zaliczka dla członków KW
          price_non_kw: Zaliczka dla pozostałych
          remarks: Uwagi od organizatora
          organizator_id: Kto organizuje?
