pl:
  activities:
    mountain_routes:
      hide:
        hidden_successfully: Ukryto!
  activerecord:
    attributes:
      training/supplementary/sign_up_record:
        fee: Składka członkowska
        name: Imię i nazwisko
        email: E-mail
        package_required: Pakiet
  training:
    activities:
      ski_routes:
        new:
          submit: dodaj turę
          back: powrót do przejść narciarskich
    supplementary:
      sign_ups:
        create:
          limit_exceded: Brak miejsc!
          not_last_fee: Musisz opłacić składkę członkowską!
      course:
        enums:
          payment_types:
            trainings: Szkolenia
            club_trips: Wyjazd klubowy
          kinds:
            other: Inne
            slides: Slajdowisko
            meeting: Spotkanie
            competitions: Zawody
            tour: Wycieczka
            training: Szkolenie
          categories:
            kw: Ogólne
            sww: Wspinaczkowe
            snw: Narciarskie
            stj: Jaskiniowe
      courses:
        index:
          header: Szkolenia, spotkania i wyjazdy
        table:
          category: Kategoria
          submit: Zapisz się!
          name: Nazwa
          place: Miejsce
          date: Data
          organizer: Koordynator
          price: Cena(zł)
          cash: Tylko gotówka?
          edit: Edycja
          show: Szczegóły
          sign_up: Zapisz się!
          limit: Zapisy
          destroy: Usuń
          sign_up_destroy: Wypisz się!
        show:
          submit: Zapisz się!
          cash: Tylko gotówka?
          later: do ustalenia
          sign_up_remarks: Twój e-mail zostanie usunięty z naszego systemu 24h po zakończeniu wydarzenia.
          sign_up: Zapisz się!
          sign_up_destroy: Wypisz się!
          category: Kategoria
          rules: Link do regulaminu wydarzeń KW Kraków
          name: Nazwa
          place: "Miejsce wydarzenia: "
          start_date: "Termin wydarzenia: "
          end_date: "Do kiedy: "
          application_date: "Rozpoczęcie zapisów: "
          organizer: "Koordynator: "
          remarks: "Uwagi od koordynatora"
          price_kw: "Cena dla klubowiczów: "
          application_price_kw: "Opłata: "
          price_non_kw: "Cena dla nie-klubowiczów: "
          edit: Edycja
          destroy: Usuń
        new:
          submit: Utwórz
          back: Cofnij
        edit:
          submit: Zaktualizuj
          back: Cofnij
        form:
          team_name: Nazwa
          last_fee_paid: Wymagaj opłaconej składki?
          category: Kategoria
          payment_type: Konto Dotpay
          place: Miejsce
          open: Nie wymagaj zapisów
          packages: Pakiety?
          start_date: Kiedy?
          price: Wymagaj zaliczki?
          one_day: Tylko jeden dzień?
          end_date: Do kiedy
          application_date: Start zapisów
          cash: Tylko gotówka?
          price_kw: Opłata dla KW
          price_non_kw: Opłata dla reszty
          remarks: Uwagi od organizatora
          organizator_id: Kto organizuje?
