default: &default
  pool: 5
  timeout: 5000
  adapter: postgresql
  encoding: unicode

production:
  <<: *default
  database: <%= ENV['PGDATABASE'] %>
  host: <%= ENV['PGHOST'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>

development:
  <<: *default
  database: kw-app_development
  username: dariusz.finster
  password: OBu8Pnq!iN

test:
  <<: *default
  database: kw-app_test
  username: dariusz.finster
  password: OBu8Pnq!iN
