default: &default
  pool: 5
  timeout: 5000
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>

production:
  <<: *default
  host: <%= ENV['PGHOST'] %>
  database: <%= ENV['PGDATABASE'] %>

development:
  <<: *default
  database: kw-app_development

test:
  <<: *default
  database: kw-app_test
