# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 137bf0b2e4688fbc131bd0de9a2ed22ef6f6039676608e4c834560cbfd407ed114143c0b13c48d1a263c076b2aca81168bfcf82a2bfc5765f853cc6fac1ab7c9
  dotpay_id: 727029
  dotpay_login: 'dariusz.finster@gmail.com'
  dotpay_password: 'siggitari0s'

test:
  secret_key_base: 70cf5f3e2305b4ccb8c329f76aea3d216873fc538ff3a85bc7bbd4269d52e59edb18eb84d13654c3932d7a867d9f769806d24da3a4de07a444e0241e17ea6841

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  dotpay_id: 447543
  dotpay_login: 'dariusz.finster@gmail.com'
  dotpay_password: <%= ENV["DOTPAY_PASSWORD"] %>
